#!/bin/bash
# Verification Guide: How to Check if OpenCode is Using Your Config

# Detect current directory and user
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OPENCODE_DIR="$REPO_DIR/opencode"

echo "═══════════════════════════════════════════════════════"
echo "🔍 How to Verify OpenCode is Using Your Configuration"
echo "═══════════════════════════════════════════════════════"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 1: Check OpenCode Startup Output"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "When you start OpenCode, look for these messages:"
echo ""
echo "✓ Skills discovered:"
echo "  Loading skills from .opencode/skill/"
echo "  • team-review"
echo "  • deploy-check"
echo "  • security-audit"
echo "  • branch"
echo "  • commit"
echo "  • push"
echo "  • create-pr"
echo ""
echo "✓ Agents discovered:"
echo "  Loading agents from .opencode/agent/"
echo "  • code-reviewer"
echo "  • test-writer"
echo ""
echo "✓ Commands discovered:"
echo "  Loading commands from .opencode/command/"
echo "  • review"
echo "  • test"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 2: Use OpenCode's Built-in Help"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In OpenCode, type:"
echo ""
echo "  /help"
echo ""
echo "This shows all available commands/skills including your custom ones."
echo ""
echo "Look for these slash commands:"
echo "  /team-review      - Review code for team standards"
echo "  /deploy-check     - Pre-deployment checklist"
echo "  /security-audit   - Security vulnerability scanning"
echo "  /review           - Custom review command"
echo "  /test             - Custom test command"
echo ""
echo "Note: Git workflow skills (branch, commit, push, create-pr) are"
echo "triggered by natural language like 'create a branch' or 'commit my changes'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 3: Check the Skill Tool Description"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Ask OpenCode:"
echo ""
echo "  \"what skills are available?\""
echo ""
echo "OpenCode should respond with:"
echo "  • team-review - Review code for team standards"
echo "  • deploy-check - Pre-deployment checklist"
echo "  • security-audit - Security vulnerability scanning"
echo "  • branch - Create a new branch"
echo "  • commit - Commit changes with good message"
echo "  • push - Push to remote"
echo "  • create-pr - Create a pull request"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 4: Check Agent Autocomplete"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In OpenCode, type: @"
echo ""
echo "You should see autocomplete suggestions:"
echo "  @code-reviewer    - Custom agent"
echo "  @test-writer      - Custom agent"
echo "  @general          - Built-in agent"
echo "  @explore          - Built-in agent"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 5: Test a Skill Directly"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Try using a skill with a slash command:"
echo ""
echo "  /team-review"
echo ""
echo "Or ask naturally:"
echo ""
echo "  \"review this code using team standards\""
echo "  \"create a branch for my feature\""
echo "  \"commit my changes\""
echo ""
echo "✓ If it works:"
echo "  OpenCode will follow the skill's instructions"
echo "  For named skills, you'll see them execute"
echo ""
echo "✗ If it doesn't work:"
echo "  Error: \"Skill 'team-review' not found\""
echo "  → Skills not loaded, check configuration"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 6: Check OpenCode Config Location"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Ask OpenCode:"
echo ""
echo "  \"where are you looking for skills?\""
echo ""
echo "OpenCode should respond with paths like:"
echo "  • $OPENCODE_DIR/.opencode/skill/"
echo "  • ~/.config/opencode/skill/"
echo "  • .claude/skills/ (compatibility)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 7: Enable Debug Mode"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Start OpenCode with debug output:"
echo ""
echo "  DEBUG=* opencode"
echo ""
echo "or"
echo ""
echo "  opencode --verbose"
echo ""
echo "Look for lines like:"
echo "  [DEBUG] Loading skill: team-review"
echo "  [DEBUG] Loading agent: code-reviewer"
echo "  [DEBUG] Loading command: review"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "UNDERSTANDING SKILLS: Named vs Natural Language"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Skills can be invoked in different ways:"
echo ""
echo "📌 Skills WITH 'name:' field (appear as slash commands):"
echo "  • team-review      → Use: /team-review"
echo "  • deploy-check     → Use: /deploy-check"
echo "  • security-audit   → Use: /security-audit"
echo ""
echo "📌 Skills WITHOUT 'name:' field (triggered by natural language):"
echo "  • branch           → Say: \"create a branch for my feature\""
echo "  • commit           → Say: \"commit my changes\""
echo "  • push             → Say: \"push to remote\""
echo "  • create-pr        → Say: \"create a pull request\""
echo ""
echo "📌 Commands (from .opencode/command/ directory):"
echo "  • review.md        → Use: /review"
echo "  • test.md          → Use: /test"
echo ""
echo "💡 Best Practice:"
echo "Add 'name:' field to SKILL.md frontmatter if you want slash command support."
echo ""
echo "Example:"
echo "  ---"
echo "  name: branch"
echo "  description: Create a new branch"
echo "  ---"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "VERIFICATION CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these tests in order:"
echo ""
echo "1. [ ] Started OpenCode in $OPENCODE_DIR"
echo "2. [ ] Saw \"Loading skills\" message on startup"
echo "3. [ ] /help shows slash commands (/team-review, /deploy-check, /security-audit, /review, /test)"
echo "4. [ ] @ shows custom agents (code-reviewer, test-writer)"
echo "5. [ ] /team-review works OR 'review this code' triggers skill"
echo "6. [ ] @code-reviewer responds"
echo "7. [ ] Natural language like 'create a branch' works"
echo ""
echo "If ALL are ✓ → Configuration is loaded and working!"
echo "If ANY are ✗ → See troubleshooting below"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TROUBLESHOOTING: Configuration Not Loading"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ PROBLEM: Skills not showing up"
echo ""
echo "CHECK 1: Are you in the right directory?"
echo "  pwd should show: $OPENCODE_DIR"
echo ""
echo "CHECK 2: Does .opencode/ exist?"
echo "  ls -la | grep .opencode"
echo ""
echo "CHECK 3: Are SKILL.md files in correct location?"
echo "  find .opencode -name \"SKILL.md\""
echo "  Should show: .opencode/skill/*/SKILL.md"
echo ""
echo "CHECK 4: Check SKILL.md frontmatter"
echo "  cat .opencode/skill/team-review/SKILL.md | head -10"
echo "  Must have: name: and description:"
echo ""
echo "CHECK 5: Restart OpenCode"
echo "  Exit and restart: opencode"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "QUICK DIAGNOSTIC SCRIPT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run this to diagnose issues:"
echo ""
cat << 'DIAGNOSTIC'
#!/bin/bash
echo "🔍 OpenCode Configuration Diagnostic"
echo ""
echo "Current directory:"
pwd
echo ""
echo ".opencode directory exists?"
if [ -d ".opencode" ]; then
    echo "✓ Yes"
else
    echo "✗ No - create it!"
fi
echo ""
echo "Skills found:"
find .opencode -name "SKILL.md" 2>/dev/null | wc -l
echo ""
echo "Agents found:"
find .opencode/agent -name "*.md" 2>/dev/null | wc -l
echo ""
echo "Commands found:"
find .opencode/command -name "*.md" 2>/dev/null | wc -l
echo ""
echo "Checking skill frontmatter:"
for skill in .opencode/skill/*/SKILL.md; do
    echo "  File: $skill"
    grep -E "^name:|^description:" "$skill" | head -2
    echo ""
done
DIAGNOSTIC
echo ""

echo "Save this as 'diagnostic.sh' and run it"
echo ""

echo "═══════════════════════════════════════════════════════"
echo "🎯 VISUAL INDICATORS THAT IT'S WORKING"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "When configuration IS loaded, you'll see:"
echo ""
echo "1. Startup Messages:"
echo "   ┌─────────────────────────────────────┐"
echo "   │ OpenCode v1.x.x                     │"
echo "   │ Loading skills from .opencode/...   │"
echo "   │ • team-review                       │"
echo "   │ • deploy-check                      │"
echo "   │ • security-audit                    │"
echo "   │ • branch                            │"
echo "   │ • commit                            │"
echo "   │ • push                              │"
echo "   │ • create-pr                         │"
echo "   │ Ready!                              │"
echo "   └─────────────────────────────────────┘"
echo ""
echo "2. Skill Invocation Works:"
echo "   You: /team-review"
echo "   OR: \"review this code using team standards\""
echo "   OpenCode: [Executes skill instructions]"
echo ""
echo "3. Agent Invocation Works:"
echo "   You: @code-reviewer review this"
echo "   OpenCode: [Invokes subagent with restrictions]"
echo ""
echo "4. Command Autocomplete:"
echo "   You: /"
echo "   OpenCode shows: /team-review, /deploy-check, /security-audit, /review, /test"
echo ""
echo "5. Natural Language Triggers:"
echo "   You: \"create a branch for authentication\""
echo "   OpenCode: [Creates branch using branch skill]"
echo ""

echo "═══════════════════════════════════════════════════════"
echo ""
echo "Ready to verify? Start OpenCode and check each method!"
echo ""
echo "═══════════════════════════════════════════════════════"
